name: hadenlabs-action-pre-commit
description: run pre-commit and optionally commit back to the pull request
author: hadenlabs
inputs:
  args:
    description: options to pass to pre-commit run
    required: false
    default: 'run --all-files'

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: validate files
      shell: bash
      run: |
        docker run --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace" hadenlabs/action-pre-commit:0.1.8 ${{ inputs.args }}

branding:
  icon: 'check-circle'
  color: "green"
