name: 'pre-commit'
description: 'run pre-commit-hooks validate code'
author: 'hadenlabs'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'

runs:
  using: 'docker'
  image: 'Dockerfile'
