name: hadenlabs-action-pre-commit
description: run pre-commit and optionally commit back to the pull request
author: hadenlabs
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: 'run --all-files'

runs:
  using: "docker"
  image: "docker://hadenlabs/action-pre-commit:0.1.5"
  args:
    - ${{ inputs.extra_args }}

branding:
  icon: 'check-circle'
  color: "green"
