name: hadenlabs-action-pre-commit
description: run pre-commit and optionally commit back to the pull request
author: hadenlabs
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: 'run --all-files'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'orange'
