# Continuous Delivery/Deployment to DockerHub
name: cd

on:
  workflow_run:
    workflows: ['test']
    types:
      - completed

  push:
    tags:
        - "v*.*.*"
    branches:
      - develop
      - main

env:
  IMAGE_NAME: 'hadenlabs/action-pre-commit'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: check out a copy of the repo
        uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      -  name: set vars to github
         run: |
          echo "APP_TAG=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            VERSION=${{ env.APP_TAG }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.APP_TAG }}

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
