name: lint-code

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

env:
  IMAGE_NAME: 'hadenlabs/action-pre-commit'

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build the docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: validate files
        run: |
          docker run --rm -w /github/workspace -v $(pwd):/github/workspace ${{ env.IMAGE_NAME }}:latest
